plugins {
    id 'com.android.application'
}

android {
    namespace 'com.adblock.app'
    compileSdk 34

    defaultConfig {
        applicationId 'com.adblock.app'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }
    buildTypes {
        release {
            minifyEnabled false
            // חתום עם מפתח debug כדי שה-APK יהיה ניתן להתקנה ישירות
            signingConfig signingConfigs.debug
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
